# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      (cd client && npm install)
      (cd server && npm install)
    command: |
      npm install nodemon -g
      (cd client && DANGEROUSLY_DISABLE_HOST_CHECK=true npm run dev)

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-browser
